version: '3.8'

services:
  backend:
    ports:
      - 3000:3000
      - 9229:9229
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - ./src:/app/src
      - ./logs:/logs